const jsonData = [
  {
    Prompt_ID: 127,
    Prompt_Category: "Minigame",
    Prompt: "_",
    Prompt_Literal: "esta pequena casa",
    Prompt_Audio: null,
    Prompt_Answer: "esta~pequena~casa",
    Prompt_Translation: "this~small~house",
    Prompt_Literal_Translation: "0~1~2",
    Prompt_Literal_Translation_Audio: null,
    Prompt_Active_Elements_ARERIR: "Article~DD~Adjective",
    Prompt_Active_Elements_Tense:
      "the--a/an/some~this/these--that/those--that(far)/those(far)~small--big",
    Prompt_Disable_Elements: "",
    Prompt_Activity_Type: "Determiners",
    Prompt_PoS: "Determiners,Adjective,Noun",
    Prompt_Activity_Instruction: "Choose the missing Portuguese word",
    Prompt_Language: "P",
    Prompt_hint_content: "",
    Set_ID: 0,
    Answer_ID: 0,
    Prompt_Options: "carro~casa~menino~menina",
    Prompt_IsDisabled: 0,
    Prompt_Instruction_Audio: null,
    Prompt_Practice_Audio: null,
    Prompt_WrongAnswer_Audio: null,
    Prompt_Instruction_Picture: null,
    Prompt_Picture: null,
    Prompt_Options2: null,
    Prompt_Template: "P1",
    Prompt_Translation1: "_~_~_",
    Prompt_Answer_State: null,
    Prompt_Exit_Answer: ["esta", "pequena", "casa"],
    Prompt_Difficulty_Level: null,
    Prompt_Tooltip_State: null,
    Prompt_Tooltip_Content: null,
    Card_IsActive: 3,
  },
  {
    Prompt_ID: 128,
    Prompt_Category: "Minigame",
    Prompt: "_",
    Prompt_Literal: "o menino pequeno",
    Prompt_Audio: null,
    Prompt_Answer: "o~menino~pequeno",
    Prompt_Translation: "the~small~boy",
    Prompt_Literal_Translation: "0~2~1",
    Prompt_Literal_Translation_Audio: null,
    Prompt_Active_Elements_ARERIR: "Article~DD~Adjective",
    Prompt_Active_Elements_Tense:
      "the--a/an/some~this/these--that/those--that(far)/those(far)~small--big",
    Prompt_Disable_Elements: "",
    Prompt_Activity_Type: "Determiners",
    Prompt_PoS: "Determiners,Noun,Adjective",
    Prompt_Activity_Instruction: "Choose the missing Portuguese word",
    Prompt_Language: "P",
    Prompt_hint_content: "",
    Set_ID: 0,
    Answer_ID: 0,
    Prompt_Options: "carro~casa~menino~menina",
    Prompt_IsDisabled: 0,
    Prompt_Instruction_Audio: null,
    Prompt_Practice_Audio: null,
    Prompt_WrongAnswer_Audio: null,
    Prompt_Instruction_Picture: null,
    Prompt_Picture: null,
    Prompt_Options2: null,
    Prompt_Template: "P1",
    Prompt_Translation1: "_~_~_",
    Prompt_Answer_State: null,
    Prompt_Exit_Answer: ["o", "menino", "pequeno"],
    Prompt_Difficulty_Level: null,
    Prompt_Tooltip_State: null,
    Prompt_Tooltip_Content: null,
    Card_IsActive: 4,
  },
  {
    Prompt_ID: 129,
    Prompt_Category: "Minigame",
    Prompt: "_ casa",
    Prompt_Literal: "da casa",
    Prompt_Audio: null,
    Prompt_Answer: "de(d+)~da",
    Prompt_Translation: "from the~house",
    Prompt_Literal_Translation: "0~1",
    Prompt_Literal_Translation_Audio: null,
    Prompt_Active_Elements_ARERIR: "Article",
    Prompt_Active_Elements_Tense: "the--a/an/some",
    Prompt_Disable_Elements: "",
    Prompt_Activity_Type: "Determiners",
    Prompt_PoS: "PrepoD,Determiners",
    Prompt_Activity_Instruction: "Select the correct preposition contraction",
    Prompt_Language: "P",
    Prompt_hint_content: "",
    Set_ID: 0,
    Answer_ID: 0,
    Prompt_Options: null,
    Prompt_IsDisabled: 0,
    Prompt_Instruction_Audio: null,
    Prompt_Practice_Audio: null,
    Prompt_WrongAnswer_Audio: null,
    Prompt_Instruction_Picture: null,
    Prompt_Picture: null,
    Prompt_Options2: "de(d+)~em(n+)~dentro de(dentro d+)",
    Prompt_Template: "P1",
    Prompt_Translation1: "_~casa",
    Prompt_Answer_State: null,
    Prompt_Exit_Answer: ["da"],
    Prompt_Difficulty_Level: null,
    Prompt_Tooltip_State: null,
    Prompt_Tooltip_Content: null,
    Card_IsActive: 5,
  },
  {
    Prompt_ID: 130,
    Prompt_Category: "Minigame",
    Prompt: "_ casa",
    Prompt_Literal: "dessa casa",
    Prompt_Audio: null,
    Prompt_Answer: "de(d+)~dessa~casa",
    Prompt_Translation: "from that~house",
    Prompt_Literal_Translation: "1~0",
    Prompt_Literal_Translation_Audio: null,
    Prompt_Active_Elements_ARERIR: "DD",
    Prompt_Active_Elements_Tense:
      "this/these--that/those--that(far)/those(far)",
    Prompt_Disable_Elements: "",
    Prompt_Activity_Type: "Determiners",
    Prompt_PoS: "PrepoD,Determiners,Noun",
    Prompt_Activity_Instruction: "Select the correct preposition contraction",
    Prompt_Language: "P",
    Prompt_hint_content: "",
    Set_ID: 0,
    Answer_ID: 0,
    Prompt_Options: "carro~casa~menino~menina",
    Prompt_IsDisabled: 0,
    Prompt_Instruction_Audio: null,
    Prompt_Practice_Audio: null,
    Prompt_WrongAnswer_Audio: null,
    Prompt_Instruction_Picture: null,
    Prompt_Picture: null,
    Prompt_Options2: "de(d+)~em(n+)~dentro de(dentro d+)",
    Prompt_Template: "P1",
    Prompt_Translation1: "_~_",
    Prompt_Answer_State: null,
    Prompt_Exit_Answer: ["dessa", "casa"],
    Prompt_Difficulty_Level: null,
    Prompt_Tooltip_State: null,
    Prompt_Tooltip_Content: null,
    Card_IsActive: 6,
  },
  {
    Prompt_ID: 131,
    Prompt_Category: "Minigame",
    Prompt: "_",
    Prompt_Literal: "dessa casa",
    Prompt_Audio: null,
    Prompt_Answer: "de(d+)~dessa",
    Prompt_Translation: "from that~house",
    Prompt_Literal_Translation: null,
    Prompt_Literal_Translation_Audio: null,
    Prompt_Active_Elements_ARERIR: "Article~DD~PD",
    Prompt_Active_Elements_Tense:
      "the--a/an/some~this/these--that/those--that(far)/those(far)~my--your--his/her/their/your(formal)--our--your(plural)",
    Prompt_Disable_Elements: "",
    Prompt_Activity_Type: "Determiners",
    Prompt_PoS: "PrepoD,Determiners",
    Prompt_Activity_Instruction: "Select the correct preposition contraction",
    Prompt_Language: "P",
    Prompt_hint_content: "",
    Set_ID: 0,
    Answer_ID: 0,
    Prompt_Options: null,
    Prompt_IsDisabled: 0,
    Prompt_Instruction_Audio: null,
    Prompt_Practice_Audio: null,
    Prompt_WrongAnswer_Audio: null,
    Prompt_Instruction_Picture: null,
    Prompt_Picture: null,
    Prompt_Options2: "de(d+)~em(n+)~dentro de(dentro d+)",
    Prompt_Template: "P1",
    Prompt_Translation1: "_~_",
    Prompt_Answer_State: null,
    Prompt_Exit_Answer: ["dessa"],
    Prompt_Difficulty_Level: null,
    Prompt_Tooltip_State: null,
    Prompt_Tooltip_Content: null,
    Card_IsActive: 7,
  },
];

export default jsonData;
